users:
  - default
  - name: vmuser
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCd2E6ui6PnPGVBHtoZ7s4SJ8BOr8KNhTDxPiLPWcoFtXtzqSUUf20YUdyYYWTXEiS3gZ3DuMu/Y1uAnyclSmiYqQeas9SA2T0s+ljmxzuYmF7a7s9ZuXWEEyY0DtL0qNleQNicKV7JUR+tSAQaKfJxHaMzzBMSDLRqvbMKbAx22A5g6IWslZ/vpsZDxFUhLRRPhyUQKIIY6R0aROiJzVe1YIoiNkrXZtkese3GZuLCxU1gAFDUUPmktZ3uY+60vRwrD8RTeeaMTZ1lH08Ew5PLI+/3k/wBsXFyUq1S7AAMQ+Cjs4PfyREgtz/+cKf8HfSWpnD3ZXNfeUwEhEWXt0iPQXN9V7HxAbuH2KIsyI4ytGC1UDiVdme3ZQ0vK1wH1ng7tjWWcu3KIxxz8OU0WMtx9XVWts3Da/UiocIrTLqb/CaXfnSs8TH4RctdH22gS4OJhW6y5dpXFfuGgqFa6GyojKFPwtvyiMiz8vhTQYb2rE+vCe5aUdkR/+zIf+1Y8ss= vmuser
