---

- name: Install required packages
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  become: true

- name: Add docker key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: true

- name: Add docker repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: true

- name: Install docker
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin
  become: true

- name: Make sure docker group exists
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: Add user vmuser to docker group 
  ansible.builtin.user:
    name: vmuser
    groups: docker
    append: yes
  become: true
  register: add_user

- name: Reboot vm
  ansible.builtin.reboot:
  become: true
  when: add_user.changed

...